Solve the readlink problem.

diff --git a/bin/cpc b/bin/cpc
--- a/bin/cpc
+++ b/bin/cpc
@@ -1,21 +1,59 @@
 #!/bin/sh
 # -*- tab-width: 4; sh-basic-offset: 4; indent-tabs-mode: t -*-
 # vim: tabstop=4 shiftwidth=4 noexpandtab
-# LICENSE: MIT
+
 # Copyright 2023 Yushun Cheng <chengys@disroot.org>
+# LICENSE: MIT
+#
+# This file is now 100% POSIX-compatible.  Please read the POSIX standard
+# carefully before making any changes!
+#
+# FYI, you can find the standard here:
+# https://pubs.opengroup.org/onlinepubs/9699919799/utilities/contents.html
+
+# Define resolpath, which should resolve the given path so that the last
+# component is not a symbolic link.
+if type realpath 1>/dev/null; then
+	resolpath() {
+		realpath "$1"
+	}
+else
+	if type readlink 1>/dev/null; then
+		resolpath() {
+			_f="$1"
+
+			while [ -L "$_f" ]; do
+				_link="$(readlink "$_f")"
+				case "$_link" in
+					/* ) _f="$_link";;
+					*  ) _f="$(dirname "$f")"/"$_link";;
+				esac
+			done
+			echo "$_f"
+
+			unset -v _f
+			unset -v _link
+		}
+	else
+		echo "readlink is not installed, so symlink resolving is unsupported" 1>&2
+		resolpath() {
+			echo "$1"
+		}
+	fi
+fi
 
 # Execute if the executable is executable.
 try_run() {
-	[ -x "$1" ] && [ -f "$1" ] && exec "$@"
+	type "$1" 1>/dev/null && exec "$@"
 }
 
 # Find the directory that contains `main.py`.
-exe_path="$(readlink -f "$0")"
+exe_path="$(resolpath "$0")"
 parent_path="$(dirname "$exe_path")"
 script_path="$parent_path/main.py"
 while ! [ -f "$script_path" ]; do
-	parent_path="$(dirname "$parent_path")"
-	script_path="$parent_path/main.py"
+	parent_path=$parent_path/..
+	script_path=$parent_path/main.py
 done
 unset -v parent_path
 unset -v exe_path
@@ -26,7 +64,7 @@ if [ $(uname -s) = "Darwin" ] && [ -d "$_MAC_PY_HOME" ]; then
 	# Search through MAC OS specific paths.
 	for path in "$_MAC_PY_HOME"/*; do
 		case $(basename "$path" | tr '[:upper:]' '[:lower:]') in
-		*pypy*) try_run "$path/bin/python3" "$script_path" "$@";;
+			*pypy*) try_run "$path/bin/python3" "$script_path" "$@";;
 		esac
 	done
 	for path in "$_MAC_PY_HOME"/*; do
@@ -36,10 +74,11 @@ if [ $(uname -s) = "Darwin" ] && [ -d "$_MAC_PY_HOME" ]; then
 		esac
 	done
 fi
+unset -v _MAC_PY_HOME
 for python in pypy3 python3; do
-	try_run "$(which "$python" 2>/dev/null)" "$script_path" "$@"
+	try_run "$python" "$script_path" "$@"
 done
 
 # If we cannot find python3, we should output a warning message.
-echo "Cannot find python3 on your computer."
-echo "Please make sure python3 is installed and added to your PATH."
+echo "cannot find python3 on your computer" 1>&2
+echo "please make sure python3 is installed and added to your PATH" 1>&2
